// admin login
export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

// admin login
export const SOCIAL_LOGIN_REQUEST = "SOCIAL_LOGIN_REQUEST";
export const SOCIAL_LOGIN_SUCCESS = "SOCIAL_LOGIN_SUCCESS";
export const SOCIAL_LOGIN_FAIL = "SOCIAL_LOGIN_FAIL";
export const SOCIAL_LOGOUT = "SOCIAL_LOGOUT";

// Lessons SignUp
export const LESSONS_REGISTER_REQUEST = "LESSONS_REGISTER_REQUEST";
export const LESSONS_REGISTER_SUCCESS = "LESSONS_REGISTER_SUCCESS";
export const LESSONS_REGISTER_FAIL = "LESSONS_REGISTER_FAIL";

// get profile details
export const ADMIN_GET_PROFILE_REQUEST = "ADMIN_GET_PROFILE_REQUEST";
export const ADMIN_GET_PROFILE_SUCCESS = "ADMIN_GET_PROFILE_SUCCESS";
export const ADMIN_GET_PROFILE_FAIL = "ADMIN_GET_PROFILE_FAIL";

// update profile
export const ADMIN_UPDATE_PROFILE_REQUEST = "ADMIN_UPDATE_PROFILE_REQUEST";
export const ADMIN_UPDATE_PROFILE_SUCCESS = "ADMIN_UPDATE_PROFILE_SUCCESS";
export const ADMIN_UPDATE_PROFILE_FAIL = "ADMIN_UPDATE_PROFILE_FAIL";
export const ADMIN_UPDATE_RESPONSE_RESET = "ADMIN_UPDATE_RESPONSE_RESET";
